model_name: Qwen3-4B
training:
  dataset_path: SftData/min_reward_threshold_None/div_threshold_0.4/fingerprint_name_ecfp6-2048/Qwen3-30B-A3B-Thinking-2507/boxed_True/molgendata_train.jsonl
  config_train: slurm/openrlhf/configs/sft_config/Qwen3-4B/0.0-0.4-qwen/train.yaml
  output_path: Qwen3-4B-0.0-0.4-qwen
evaluation:
  dataset_eval: molgendata
  eval_config: slurm/openrlhf/configs/sft_config/Qwen3-4B/0.0-0.4-qwen/eval.yaml
